######################################################################
# Automatically generated by qmake (3.0) ?? 1? 14 22:28:56 2017
######################################################################

TEMPLATE = app
TARGET = Client
INCLUDEPATH += .

# Input
SOURCES += main.cpp
