######################################################################
# Automatically generated by qmake (3.0) ?? 1? 14 22:29:24 2017
######################################################################

QT+=network widgets gui

TEMPLATE = app
TARGET = Server
INCLUDEPATH += $$PWD/../public/

# Input
SOURCES += main.cpp \
    sock.cpp \
    manager.cpp

HEADERS += \
    sock.h \
    ../public/dts.h \
    manager.h

